#page title
page_title                                : WorthTracker - Track your net worth

# App Info
ios_app_id                                : 1517288542  # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.applitom.worthtracker
presskit_download_link                    : http://applitom.com/#contact

app_icon                                  : assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : WorthTracker
app_price                                 : Track your net worth
app_description                           : WorthTracker makes it easy to track your net worth.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Applitom                                
your_link                                 : http://applitom.com                     
your_city                                 : 
email_address                             : worthtrackerapp@gmail.com
facebook_username                         : worthtracker                                          
instagram_username                        : worthtracker
twitter_username                          : worthtracker
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  : 

  - title                                 : Calculate your total net worth
    description                           : WorthTracker makes it easy for you to track your net worth.
    fontawesome_icon_name                 : coins

  - title                                 : Track & Manage assets
    description                           : Manage all of your asset types such as real estate, banking accounts, stock portfolio, etc.
    fontawesome_icon_name                 : plus

  - title                                 : Track & Manage liabilities
    description                           : Don't forget to track everything you owe as well, such as loans and mortgages.
    fontawesome_icon_name                 : minus

  - title                                 : Keep Historic Data
    description                           : Keep your portfolio updated over time, and WorthTracker will help you to see your progress over time.
    fontawesome_icon_name                 : database

  - title                                 : Your net worth visualizations
    description                           : See visualizations and progress graph of your net worth
    fontawesome_icon_name                 : chart-line

  - title                                 : Back up
    description                           : Your data is backed up and synced across all of your devices
    fontawesome_icon_name                 : sync

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.2
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

keep_files:
  - api/

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown